# Podem crear cadascuna de les imatges per a la nostra aplicació 
# a partir del Dockerfile que té cada una de les carpetes
# o bé amb compose aixecar-los tots de cop i que facin referencina
# al codi que tenim just en aquest moment.

# Recordeu que si creem les imatges, el codi no s'actualitza fins
# que no tornem a crear la imatge. Els fitxers "Dockerfile" copien
# a dins de la imatge el codi font corresponent. 
# Per això, si volem que s'actualitzi
# cada cop que engeguem el contenidor, hem de fer servir aquest compose
# que monta el codi de la nostra aplicació com un volum per a cadascuna de les imatges


version: '3'
services:
  node:
    image: node:19-buster-slim
    volumes:
      - ./node:/home/node/app
    ports:
      - 8080:8080

  httpd:
    build: ./front
    volumes:
      - ./front:/home/node/app
    ports:
      - 80:80
    depends_on:
      - node

db:
  image: mysql:8.2.0
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: persones
    MYSQL_USER: user
    MYSQL_PASSWORD: user
  ports:
    - 3306:3306
  volumes:
    - mysql_data:/var/lib/mysql
    - ./mysql/dades.sql:/docker-entrypoint-initdb.d/dades.sql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "9090:80"
  depends_on:
    - db

volumes:
  mysql_data:
